set -g base-index 1           # windows numbered from 1
set -g pane-base-index 1      # panes numbered from 1
set -g focus-events on
set-option -g focus-events on
set -g mouse on

set -g extended-keys always     # was 'on'; needed so pi gets Shift+Enter as CSI-u
set -g extended-keys-format csi-u

set -g set-clipboard on
set -gq allow-passthrough on

# set -g visual-activity off

# transparent status line (inherits terminal background)
set -g status-style bg=default
set -g window-status-current-style bg=default
set -g window-status-style bg=default

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

bind-key -n C-S-Left  previous-window
bind-key -n C-S-Right next-window

run '~/.tmux/plugins/tpm/tpm'

# Tell tmux that Kitty can send extended keys like Shift+Enter
set -as terminal-features ',xterm-kitty:extkeys'
